#!/bin/bash
LXC_DATADIRECTORY="$(cat /boot/config/plugins/lxc/lxc.conf | grep -n "lxc.lxcpath" | cut -d '=' -f2 | sed 's/\"//g')"
if [ ! -d ${LXC_DATADIRECTORY}/cache ]; then
  mkdir -p ${LXC_DATADIRECTORY}/cache
fi
ln -s ${LXC_DATADIRECTORY}/cache /var/cache/lxc 2>/dev/null
if [ "$(cat /boot/config/plugins/lxc/plugin.cfg | grep -n "SERVICE" | cut -d '=' -f2 | sed 's/\"//g')" == "enabled" ]; then
  logger "LXC: Executing autostart from container(s)"
  lxc-autostart
fi
